extends SceneTree

# Writes docs/balance.md from the live catalogs, so the table cannot drift from
# the numbers the game actually runs on:
#
#   godot --headless --path godot --script tools/balance_table.gd
#
# Where a number is derived rather than catalogued, the derivation is stated in
# the report. Nothing here is a judgement about what the balance *should* be -
# it lays the numbers out and flags the ones that disagree with each other.

const OUT = "res://docs/balance.md"
# Waves worth tabulating: the opening, each boss, and the shape in between.
const SAMPLE_WAVES = [1,3,5,7,10,13,15,20,25,30,40,50]
# A nominal crowd size for comparing area weapons against single-target ones.
# Melee and chain have no real cap; this is only so the columns are comparable.
const CROWD = 3.0

var out = ""
# Filled by _melee_reality so _flags can report the divergence it measures.
var rig_rates: Array = []

func line(text: String=""):
	out+=text+"\n"

func num(value: float,places: int=1) -> String:
	return String.num(value,places)

func _initialize():call_deferred("build")

# What a weapon does per second before any class touches it. Focus is everything
# it can land on one body; spread is everything it can land at all.
func weapon_profile(w: Dictionary) -> Dictionary:
	var behavior=w.get("behavior","singleProjectile")
	var focus_hits=1.0
	var spread_hits=1.0
	match behavior:
		"spread":
			# Every pellet can land on one body at point blank.
			focus_hits=float(w.get("projectileCount",1))
			spread_hits=float(w.get("projectileCount",1))
		"piercing":
			# A pierce passes through to the next body; it cannot hit one twice.
			spread_hits=1.0+float(w.get("pierceCount",0))
		"chain":
			# _chain runs chainCount+1 links, each on a different body.
			spread_hits=float(w.get("chainCount",0))+1.0
		"melee":
			# A swing is an area, so its reach over a crowd is uncapped.
			spread_hits=CROWD
	var rate=float(w.attacksPerSecond)
	return {"focus":float(w.damage)*rate*focus_hits,"spread":float(w.damage)*rate*spread_hits,
		"behavior":behavior,"rate":rate}

# The expected multiplier a crit chance is worth over a long fight.
func crit_multiplier(stats: Dictionary) -> float:
	return 1.0+stats.criticalChance*(stats.criticalDamage-1.0)

# How much of a hit a class actually takes, once armour and dodge are counted.
func effective_hp(stats: Dictionary) -> float:
	return stats.maxHp/maxf(0.01,(1.0-stats.armor)*(1.0-stats.dodgeChance))

func build():
	BWData.load_catalogs()
	line("# Balance table")
	line()
	line("Generated by `tools/balance_table.gd` from `data/catalogs.json` and")
	line("`scripts/data.gd`. Regenerate it rather than editing it by hand:")
	line()
	line("```sh")
	line("godot --headless --path godot --script tools/balance_table.gd")
	line("```")
	line()
	line("Damage figures are per second and ignore upgrades, shop items and the")
	line("permanent tree - this is the floor every run starts from.")
	line()

	_weapons()
	_classes()
	_enemies()
	_waves()
	await _melee_reality()
	_flags()

	var handle=FileAccess.open(OUT,FileAccess.WRITE)
	if handle==null:
		push_error("cannot write "+OUT)
		quit(1)
		return
	handle.store_string(out)
	handle.close()
	print("BALANCE_TABLE_WRITTEN ",OUT," ",out.split("\n").size()," lines")
	quit(0)

func _weapons():
	line("## Weapons")
	line()
	line("`Focus` is damage per second onto a single body. `Spread` is the most it")
	line("can put out across several, with melee and chain measured over %d." % int(CROWD))
	line()
	line("| Weapon | Behaviour | Hit dmg | /sec | Focus DPS | Spread DPS | Range (m) |")
	line("| --- | --- | ---: | ---: | ---: | ---: | ---: |")
	for w in BWData.rows("weapons"):
		var p=weapon_profile(w)
		line("| %s | %s | %s | %s | %s | %s | %s |" % [w.name,p.behavior,num(float(w.damage)),
			num(p.rate,2),num(p.focus),num(p.spread),num(float(w.range)*BWData.UNIT)])
	line()

func _classes():
	line("## Classes")
	line()
	line("Effective DPS folds in the class damage stat, its attack speed and the")
	line("expected value of its crit. Effective HP folds armour and dodge into the")
	line("health pool, so the columns are comparable across classes.")
	line()
	line("| Class | Weapon | Dmg x | Spd x | Crit | Crit x | Focus DPS | Spread DPS | HP | Eff. HP | Speed |")
	line("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
	for id in BWData.CLASSES:
		var row=BWData.CLASSES[id]
		var stats=BWData.stats(id)
		var weapon=BWData.entry("weapons",row.weapon)
		var p=weapon_profile(weapon)
		var scale=stats.damage*stats.attackSpeed*crit_multiplier(stats)
		line("| %s | %s | %s | %s | %d%% / %sx | %s | %s | %s | %s | %s | %s |" % [row.name,weapon.name,
			num(stats.damage,2),num(stats.attackSpeed,2),int(round(stats.criticalChance*100)),
			num(stats.criticalDamage,1),num(crit_multiplier(stats),2),
			num(p.focus*scale),num(p.spread*scale),num(stats.maxHp,0),num(effective_hp(stats),0),
			num(stats.moveSpeed,0)])
	line()

func _enemies():
	line("## Enemies (base, wave 1)")
	line()
	line("Threat is damage per second while a body is in contact and swinging.")
	line("Reward per HP is how much experience a point of enemy health returns -")
	line("a type well above the others pays out faster than it costs to kill.")
	line()
	line("| Enemy | HP | Hit | Cooldown | Threat/s | Speed | Range (m) | XP | Gold | XP/HP | Unlock | Weight |")
	line("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
	for e in BWData.rows("enemies"):
		var cooldown=maxf(0.01,float(e.attackCooldown))
		var threat=float(e.damage)/cooldown
		line("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % [e.id,num(float(e.maxHp),0),
			num(float(e.damage),0),num(cooldown,2),num(threat),num(float(e.moveSpeed),0),
			num(float(e.attackRange)*BWData.UNIT,2),num(float(e.xpReward),0),num(float(e.goldReward),0),
			num(float(e.xpReward)/maxf(1.0,float(e.maxHp)),2),
			str(int(e.get("unlockWave",0))) if e.has("unlockWave") else "-",
			str(int(e.get("spawnWeight",0))) if e.has("spawnWeight") else "-"])
	line()

func _waves():
	line("## Wave curve")
	line()
	line("`Grunt HP` and `Tank HP` are the catalogued value times the wave")
	line("multiplier. `Elite HP` is a grunt at the same wave with the elite bonus")
	line("on top. Time-to-kill is a starting class's focus DPS against one grunt,")
	line("with no upgrades at all - the pessimistic end of the range.")
	line()
	var header="| Wave | Quota | Cap | Interval | Elite | Mult | Grunt HP | Tank HP | Elite HP |"
	var rule="| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
	for id in BWData.CLASSES:
		header+=" TTK %s |" % BWData.CLASSES[id].name
		rule+=" ---: |"
	line(header)
	line(rule)
	var grunt=BWData.entry("enemies","grunt")
	var tank=BWData.entry("enemies","tank")
	for wave in SAMPLE_WAVES:
		var rules=BWData.wave_rules(wave)
		var grunt_hp=float(grunt.maxHp)*rules.multiplier
		var row="| %d | %d | %d | %s | %d%% | %sx | %s | %s | %s |" % [wave,int(rules.quota),int(rules.cap),
			num(rules.interval,2),int(round(rules.elite*100)),num(rules.multiplier,2),
			num(grunt_hp,0),num(float(tank.maxHp)*rules.multiplier,0),num(grunt_hp*2.5,0)]
		for id in BWData.CLASSES:
			var stats=BWData.stats(id)
			var p=weapon_profile(BWData.entry("weapons",BWData.CLASSES[id].weapon))
			var dps=p.focus*stats.damage*stats.attackSpeed*crit_multiplier(stats)
			row+=" %ss |" % num(grunt_hp/maxf(0.01,dps),2)
		line(row)
	line()

	line("### Boss")
	line()
	var boss=BWData.entry("enemies","boss")
	line("The boss does not take the wave multiplier - it is a flat %s HP at every" % num(float(boss.maxHp),0))
	line("boss wave, which is every tenth. Time to kill it, on starting damage alone:")
	line()
	line("| Class | Focus DPS | Boss TTK |")
	line("| --- | ---: | ---: |")
	for id in BWData.CLASSES:
		var stats=BWData.stats(id)
		var p=weapon_profile(BWData.entry("weapons",BWData.CLASSES[id].weapon))
		var dps=p.focus*stats.damage*stats.attackSpeed*crit_multiplier(stats)
		line("| %s | %s | %ss |" % [BWData.CLASSES[id].name,num(dps),num(float(boss.maxHp)/maxf(0.01,dps),1)])
	line()

# The catalogued attacksPerSecond is not what a fitted rig delivers: a melee
# swing is also gated by its own clip, so the chain can be slower than the
# number the tables above are built on. Measure it off the rigs.
func _melee_reality():
	line("## Melee: catalogue against clip")
	line()
	line("A class whose rig carries fitted timing plays its swing at the pace the")
	line("animation was authored at, and cannot start the next link until the")
	line("cancel window opens. Where that gate is slower than the weapon cooldown,")
	line("the catalogued rate is not the rate the player gets.")
	line()
	var scene=load("res://scenes/main.tscn").instantiate()
	root.add_child(scene)
	await process_frame
	scene.meta=BWMeta.new();scene.meta.path="user://balance_table_scratch.json"
	for id in BWData.CLASSES:
		var weapon=BWData.entry("weapons",BWData.CLASSES[id].weapon)
		if weapon.get("behavior","")!="melee":continue
		scene.start_run(id)
		await process_frame
		var visual=scene.world.visual
		if not visual.fitted_timing:
			line("- **%s** - rig has no fitted timing, so the catalogue rate stands." % BWData.CLASSES[id].name)
			continue
		var stats=BWData.stats(id)
		var cooldown=1.0/(float(weapon.attacksPerSecond)*stats.attackSpeed)
		var pace=BWWorld.combo_pace*clampf(stats.attackSpeed,0.8,1.5)
		line("**%s** - catalogue %s/s (%ss between swings):" % [BWData.CLASSES[id].name,
			num(float(weapon.attacksPerSecond),2),num(cooldown,3)])
		line()
		# A rig may be fitted without carrying the chain: _weapons falls back to the
		# plain attack clip, which is still played at its authored pace.
		var chain=[]
		for clip in BWWorld.COMBO:
			if visual.clips.has(clip):chain.append(clip)
		if chain.is_empty():
			chain=["attack"]
			line("This rig carries no chain clips, so every swing is the one `attack`")
			line("clip, played at the pace it was authored at.")
			line()
		line("| Swing | Clip (s) | Played (s) | Cancel gate (s) | Actual gap (s) |")
		line("| --- | ---: | ---: | ---: | ---: |")
		var chain_total=0.0
		var links=0
		for clip in chain:
			if not visual.clips.has(clip):continue
			var authored=visual.clip_length(clip)
			var played=authored/pace
			var gate=played*BWWorld.CANCEL
			var actual=maxf(cooldown,gate)
			chain_total+=actual
			links+=1
			line("| %s | %s | %s | %s | %s |" % [clip,num(authored,3),num(played,3),num(gate,3),num(actual,3)])
		line()
		if links>0:
			var real_rate=float(links)/chain_total
			var catalogued=float(weapon.attacksPerSecond)*stats.attackSpeed
			line("A full cycle of %d swing(s) takes **%ss**, so the sustained rate is" % [links,num(chain_total,2)])
			line("**%s swings/s** against a catalogued **%s/s** - the player gets **%s%%**" % [num(real_rate,2),
				num(catalogued,2),num(real_rate/catalogued*100.0,0)])
			line("of the table figure, and every DPS number above for this class is")
			line("overstated by the same margin.")
			line()
			var p=weapon_profile(weapon)
			var scale=stats.damage*stats.attackSpeed*crit_multiplier(stats)
			var listed=p.focus*scale
			rig_rates.append({"name":BWData.CLASSES[id].name,"real":real_rate,"listed":catalogued,
				"dps_listed":listed,"dps_real":listed*real_rate/catalogued,"chained":chain.size()>1})
			line("| | Focus DPS |")
			line("| --- | ---: |")
			line("| As catalogued | %s |" % num(listed))
			line("| As the rig plays it | %s |" % num(listed*real_rate/catalogued))
			line()
		scene.show_menu()
		await process_frame
	scene.queue_free()
	await process_frame

# Numbers that disagree with each other. Each of these is stated as what it is,
# not as a verdict - whether any of them is wrong is a design call.
func _flags():
	line("## Disagreements worth a look")
	line()
	var notes=[]

	# The gap between a catalogued rate and the one the animation allows. This is
	# the only figure here the catalogs cannot show on their own.
	rig_rates.sort_custom(func(a,b):return a.real/a.listed<b.real/b.listed)
	for rig in rig_rates:
		var share=rig.real/rig.listed*100.0
		if share>=95.0:continue
		notes.append("**%s** only gets **%s%%** of its catalogued attack rate: the animation gates it to %s swings/s against %s/s on the row, so its real opening DPS is **%s**, not the %s the tables above show.%s" % [
			rig.name,num(share,0),num(rig.real,2),num(rig.listed,2),num(rig.dps_real),num(rig.dps_listed),
			"" if rig.chained else " This rig has no chain clips, so one long swing sets the whole tempo."])

	# Classes whose opening DPS is far from the pack.
	var best={"id":"","dps":-1.0}
	var worst={"id":"","dps":1e9}
	for id in BWData.CLASSES:
		var stats=BWData.stats(id)
		var p=weapon_profile(BWData.entry("weapons",BWData.CLASSES[id].weapon))
		var dps=p.focus*stats.damage*stats.attackSpeed*crit_multiplier(stats)
		if dps>best.dps:best={"id":id,"dps":dps}
		if dps<worst.dps:worst={"id":id,"dps":dps}
	if worst.dps>0.0 and best.dps/worst.dps>=1.5:
		notes.append("Opening single-target DPS spans **%sx**: %s at %s, %s at %s. Everything else being equal, that is how much longer the weakest class holds each body in front of it. Note this uses catalogued rates; see the rig figures above." % [
			num(best.dps/worst.dps,2),BWData.CLASSES[best.id].name,num(best.dps),
			BWData.CLASSES[worst.id].name,num(worst.dps)])

	# Survivability spread.
	var tough={"id":"","hp":-1.0}
	var frail={"id":"","hp":1e9}
	for id in BWData.CLASSES:
		var hp=effective_hp(BWData.stats(id))
		if hp>tough.hp:tough={"id":id,"hp":hp}
		if hp<frail.hp:frail={"id":id,"hp":hp}
	notes.append("Effective health spans **%sx**, %s at %s down to %s at %s." % [
		num(tough.hp/maxf(1.0,frail.hp),2),BWData.CLASSES[tough.id].name,num(tough.hp,0),
		BWData.CLASSES[frail.id].name,num(frail.hp,0)])

	# A reward that is cheap relative to what it takes to kill.
	var ratios=[]
	for e in BWData.rows("enemies"):
		if e.id=="boss":continue
		ratios.append({"id":e.id,"ratio":float(e.xpReward)/maxf(1.0,float(e.maxHp))})
	ratios.sort_custom(func(a,b):return a.ratio>b.ratio)
	if ratios.size()>1 and ratios[0].ratio/maxf(0.001,ratios[-1].ratio)>=2.0:
		notes.append("Experience per point of health spans **%sx**: %s pays %s per HP, %s only %s. Waves that lean on the cheap end level the player noticeably faster." % [
			num(ratios[0].ratio/ratios[-1].ratio,2),ratios[0].id,num(ratios[0].ratio,2),
			ratios[-1].id,num(ratios[-1].ratio,2)])

	# The boss does not scale, so it gets relatively easier as the run goes on.
	var boss=BWData.entry("enemies","boss")
	var grunt=BWData.entry("enemies","grunt")
	var first=BWData.wave_rules(10).multiplier
	var later=BWData.wave_rules(50).multiplier
	notes.append("The boss is a flat %s HP at every boss wave while an ordinary grunt goes from %s HP at wave 10 to %s at wave 50. The first boss is worth **%s grunts**, the fifth-from-last **%s** - relative to the wave around it, the boss gets steadily easier." % [
		num(float(boss.maxHp),0),num(float(grunt.maxHp)*first,0),num(float(grunt.maxHp)*later,0),
		num(float(boss.maxHp)/(float(grunt.maxHp)*first),0),num(float(boss.maxHp)/(float(grunt.maxHp)*later),0)])

	# Where the spawn cap stops being the thing that limits a wave.
	for wave in range(1,200):
		var rules=BWData.wave_rules(wave)
		if rules.cap>=20:
			notes.append("The spawn cap tops out at 20 from **wave %d**, and the interval bottoms out at %ss from **wave %d**. Past those, a wave gets longer rather than denser - the quota keeps climbing but the pressure on screen does not." % [
				wave,num(BWData.wave_rules(999).interval,2),_interval_floor()])
			break

	# A healer that outheals what a class can put into it is a stall.
	var healer=BWData.entry("enemies","healer")
	if not healer.is_empty():
		var heal_rate=float(healer.healAmount)/maxf(0.01,float(healer.attackCooldown))
		notes.append("A healer restores **%s HP/s** to one ally (%s in an elite). Against the slowest opening class that is %s%% of its whole single-target output, so an unfocused healer can stall a wave outright." % [
			num(heal_rate),num(heal_rate*2.5),num(heal_rate/maxf(0.01,worst.dps)*100.0,0)])

	for note in notes:
		line("- "+note)
	line()

func _interval_floor() -> int:
	for wave in range(1,500):
		if BWData.wave_rules(wave).interval<=0.35:return wave
	return -1
